@hostname = https://jsonplaceholder.typicode.com

### Get all todos
GET {{hostname}}/todos HTTP/1.1

### Get a single todo
GET {{hostname}}/todos/1 HTTP/1.1

### Get all todos for a user
GET {{hostname}}/todos?userId=1 HTTP/1.1
